apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ticketing
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: joelmusicman/auth
          env:
            - name: JWT_SIGNING_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SIGNING_KEY
            - name: MONGO_CONNECTION_URI
              value: mongodb://auth-mongo-srv:27017/auth
---
apiVersion: v1
kind: Service
metadata:
  name: auth-clusterip-srv
  namespace: ticketing
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
  namespace: ticketing
spec:
  type: NodePort
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000