apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-depl
  namespace: ticketing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: joelmusicman/orders
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: http://nats-srv:4222
            - name: NATS_CLUSTER_ID
              value: ticketing-app
            - name: JWT_SIGNING_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SIGNING_KEY
            - name: MONGO_CONNECTION_URI
              value: mongodb://orders-mongo-srv:27017/orders
---
apiVersion: v1
kind: Service
metadata:
  name: orders-clusterip-srv
  namespace: ticketing
spec:
  type: ClusterIP
  selector:
    app: orders
  ports:
    - name: orders
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: orders-srv
  namespace: ticketing
spec:
  type: NodePort
  selector:
    app: orders
  ports:
    - name: orders
      protocol: TCP
      port: 3000
      targetPort: 3000