apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-depl
  namespace: ticketing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketing
  template:
    metadata:
      labels:
        app: ticketing
    spec:
      containers:
        - name: ticketing
          image: joelmusicman/ticketing
          env:
            - name: JWT_SIGNING_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SIGNING_KEY
            - name: MONGO_CONNECTION_URI
              value: mongodb://ticketing-mongo-srv:27017/ticketing
---
apiVersion: v1
kind: Service
metadata:
  name: ticketing-clusterip-srv
  namespace: ticketing
spec:
  type: ClusterIP
  selector:
    app: ticketing
  ports:
    - name: ticketing
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ticketing-srv
  namespace: ticketing
spec:
  type: NodePort
  selector:
    app: ticketing
  ports:
    - name: ticketing
      protocol: TCP
      port: 3000
      targetPort: 3000